#!/usr/bin/env tsx
/**
 * Turkish Law MCP -- Ingestion Pipeline
 *
 * Fetches Turkish legislation from mevzuat.gov.tr (Presidency Legislation
 * Information System). Downloads the iframe content page for each law and
 * parses the structured HTML into provision-level JSON seed files.
 *
 * **Census-driven**: Reads data/census.json (generated by scripts/census.ts) to
 * enumerate ALL Turkish laws. Falls back to KEY_TURKISH_ACTS if census is missing.
 *
 * Usage:
 *   npm run ingest                    # Full ingestion (from census)
 *   npm run ingest -- --limit 5       # Test with 5 acts
 *   npm run ingest -- --skip-fetch    # Reuse cached HTML
 *   npm run ingest -- --resume        # Skip acts that already have seed files
 *
 * Data source: mevzuat.gov.tr (Cumhurbaşkanlığı Mevzuat Bilgi Sistemi)
 * License: Government Public Data
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchMevzuatContent } from './lib/fetcher.js';
import { parseTurkishHtml, KEY_TURKISH_ACTS, type ActIndexEntry, type ParsedAct } from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

interface CensusLaw {
  id: string;
  mevzuatNo: string;
  mevzuatTur: number;
  mevzuatTertip: number;
  title: string;
  type: 'kanun' | 'khk' | 'cumhurbaskanligi_kararnamesi';
  gazetteDate: string;
  gazetteNumber: string;
  acceptanceDate: string;
  url: string;
  classification: 'ingestable' | 'inaccessible' | 'metadata_only';
  repealed: boolean;
  repealedBy: string | null;
}

interface CensusData {
  generated_at: string;
  stats: {
    total: number;
    class_ingestable: number;
    class_inaccessible: number;
    class_metadata_only: number;
  };
  ingestion?: {
    completed_at: string;
    total_laws: number;
    total_provisions: number;
    coverage_pct: string;
  };
  laws: CensusLaw[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Convert a census law entry into the ActIndexEntry format used by the parser.
 */
function censusLawToIndexEntry(censusLaw: CensusLaw): ActIndexEntry {
  const shortName = censusLaw.title.length > 40
    ? censusLaw.title.substring(0, 37) + '...'
    : censusLaw.title;

  return {
    id: censusLaw.id,
    mevzuatNo: censusLaw.mevzuatNo,
    mevzuatTur: censusLaw.mevzuatTur,
    mevzuatTertip: censusLaw.mevzuatTertip,
    title: censusLaw.title,
    shortName,
    status: censusLaw.repealed ? 'repealed' : 'in_force',
    gazetteDate: censusLaw.gazetteDate,
    gazetteNumber: censusLaw.gazetteNumber,
    acceptanceDate: censusLaw.acceptanceDate,
    url: censusLaw.url,
  };
}

/**
 * Load acts from census.json if available, otherwise fall back to KEY_TURKISH_ACTS.
 */
function loadActList(): ActIndexEntry[] {
  if (fs.existsSync(CENSUS_PATH)) {
    const raw = fs.readFileSync(CENSUS_PATH, 'utf-8');
    const census = JSON.parse(raw) as CensusData;

    console.log(`  Census: ${census.stats.total} laws (generated ${census.generated_at})`);

    // Only include ingestable acts
    const ingestable = census.laws.filter(a => a.classification === 'ingestable');
    console.log(`  Ingestable: ${ingestable.length} laws`);

    return ingestable.map(censusLawToIndexEntry);
  }

  console.log('  WARNING: No census.json found -- falling back to KEY_TURKISH_ACTS (3 acts)');
  console.log('  Run: npx tsx scripts/census.ts   to generate full census\n');
  return KEY_TURKISH_ACTS;
}

async function fetchAndParseActs(acts: ActIndexEntry[], skipFetch: boolean, resume: boolean): Promise<void> {
  console.log(`\nProcessing ${acts.length} Turkish laws...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let skipped = 0;
  let resumed = 0;
  let failed = 0;
  let emptyContent = 0;
  let totalProvisions = 0;
  let totalDefinitions = 0;
  const startTime = Date.now();

  const report: { act: string; provisions: number; definitions: number; status: string }[] = [];

  for (const act of acts) {
    const sourceFile = path.join(SOURCE_DIR, `${act.id}.html`);
    const seedFile = path.join(SEED_DIR, `${act.id}.json`);

    // Resume support: skip acts that already have seed files
    if (resume && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
        resumed++;
        processed++;
        continue;
      } catch {
        // Corrupted seed file, re-ingest
      }
    }

    // Skip if seed already exists and we're in skip-fetch mode
    if (skipFetch && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        report.push({
          act: act.shortName ?? act.id,
          provisions: existing.provisions.length,
          definitions: existing.definitions.length,
          status: 'cached',
        });
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
        skipped++;
        processed++;
        continue;
      } catch {
        // Corrupted seed file, re-ingest
      }
    }

    try {
      let html: string;

      if (fs.existsSync(sourceFile) && skipFetch) {
        html = fs.readFileSync(sourceFile, 'utf-8');
        console.log(`  Using cached ${act.shortName ?? act.id} (${act.mevzuatNo})`);
      } else {
        process.stdout.write(`  [${processed + 1}/${acts.length}] Fetching ${act.mevzuatNo} (Tur=${act.mevzuatTur})...`);
        const result = await fetchMevzuatContent(act.mevzuatNo, act.mevzuatTur, act.mevzuatTertip);

        if (result.status !== 200) {
          console.log(` HTTP ${result.status} -- SKIPPED`);
          report.push({ act: act.shortName ?? act.id, provisions: 0, definitions: 0, status: `HTTP ${result.status}` });
          failed++;
          processed++;
          continue;
        }

        // Check for empty or error content
        if (result.body.length < 500 || result.body.includes('Bir hata olu')) {
          console.log(` EMPTY/ERROR -- SKIPPED`);
          report.push({ act: act.shortName ?? act.id, provisions: 0, definitions: 0, status: 'empty/error' });
          emptyContent++;
          failed++;
          processed++;
          continue;
        }

        html = result.body;
        fs.writeFileSync(sourceFile, html);
        console.log(` OK (${(html.length / 1024).toFixed(0)} KB)`);
      }

      const parsed = parseTurkishHtml(html, act);
      fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));

      totalProvisions += parsed.provisions.length;
      totalDefinitions += parsed.definitions.length;

      report.push({
        act: act.shortName ?? act.id,
        provisions: parsed.provisions.length,
        definitions: parsed.definitions.length,
        status: 'OK',
      });

      console.log(`    -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.log(`  ERROR parsing ${act.shortName ?? act.id}: ${msg}`);
      report.push({ act: act.shortName ?? act.id, provisions: 0, definitions: 0, status: `ERROR: ${msg}` });
      failed++;
    }

    processed++;

    // Progress log every 50 acts
    if (processed % 50 === 0) {
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
      const eta = ((Date.now() - startTime) / processed * (acts.length - processed) / 1000).toFixed(0);
      console.log(`\n  --- Progress: ${processed}/${acts.length} (${elapsed}s elapsed, ~${eta}s remaining) ---\n`);
    }
  }

  const totalElapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Print summary report
  console.log(`\n${'='.repeat(70)}`);
  console.log('INGESTION REPORT');
  console.log('='.repeat(70));

  if (report.length <= 100) {
    console.log(`${'Act'.padEnd(40)} ${'Prov'.padEnd(8)} ${'Defs'.padEnd(8)} Status`);
    console.log('-'.repeat(70));
    for (const r of report) {
      console.log(
        `${r.act.substring(0, 39).padEnd(40)} ${String(r.provisions).padEnd(8)} ${String(r.definitions).padEnd(8)} ${r.status}`
      );
    }
    console.log('-'.repeat(70));
  } else {
    const okCount = report.filter(r => r.status === 'OK').length;
    const failedCount = report.filter(r => r.status !== 'OK' && r.status !== 'cached').length;
    const cachedCount = report.filter(r => r.status === 'cached').length;
    console.log(`  New ingestions:  ${okCount}`);
    console.log(`  Cached:          ${cachedCount}`);
    console.log(`  Failed:          ${failedCount}`);
    if (failedCount > 0) {
      console.log('\n  Failed acts:');
      for (const r of report.filter(r => r.status !== 'OK' && r.status !== 'cached')) {
        console.log(`    ${r.act.substring(0, 39).padEnd(40)} ${r.status}`);
      }
    }
  }

  console.log(`\n${'='.repeat(70)}`);
  console.log(`  Total elapsed:     ${totalElapsed}s`);
  console.log(`  Acts processed:    ${processed}`);
  console.log(`  Acts resumed:      ${resumed}`);
  console.log(`  Acts cached:       ${skipped}`);
  console.log(`  Acts failed:       ${failed}`);
  console.log(`  Empty/error:       ${emptyContent}`);
  console.log(`  Total provisions:  ${totalProvisions}`);
  console.log(`  Total definitions: ${totalDefinitions}`);

  // Update census.json with ingestion stats
  if (fs.existsSync(CENSUS_PATH)) {
    const census = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
    census.ingestion = {
      completed_at: new Date().toISOString(),
      total_laws: processed - failed,
      total_provisions: totalProvisions,
      coverage_pct: ((processed - failed) / acts.length * 100).toFixed(1),
    };

    // Update classification for failed acts
    if (failed > 0) {
      const failedReport = report.filter(r => r.status.startsWith('HTTP') || r.status === 'empty/error');
      for (const fr of failedReport) {
        const censusLaw = census.laws?.find((a: CensusLaw) => a.title.startsWith(fr.act.substring(0, 30)));
        if (censusLaw) {
          censusLaw.classification = 'inaccessible';
        }
      }
      if (census.stats) {
        census.stats.class_ingestable = census.laws?.filter((a: CensusLaw) => a.classification === 'ingestable').length ?? 0;
        census.stats.class_inaccessible = census.laws?.filter((a: CensusLaw) => a.classification === 'inaccessible').length ?? 0;
      }
    }

    fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2) + '\n');
    console.log(`\n  Updated census.json with ingestion stats.`);
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('Turkish Law MCP -- Ingestion Pipeline');
  console.log('=====================================\n');
  console.log(`  Source:  mevzuat.gov.tr (Cumhurbaşkanlığı Mevzuat Bilgi Sistemi)`);
  console.log(`  Method:  MevzuatFihristDetayIframe (structured HTML)`);
  console.log(`  License: Government Public Data`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);
  if (resume) console.log(`  --resume (skip existing seed files)`);

  const allActs = loadActList();
  const acts = limit ? allActs.slice(0, limit) : allActs;
  await fetchAndParseActs(acts, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
